#
# Rails To-Do App - App Platform Specification
# DigitalOcean App Platform configuration for Ruby on Rails with hot-reload
#

name: rails-todo-dev
region: nyc

services:
  - name: rails-app
    # Use hot-reload-template Dockerfile
    dockerfile_path: hot-reload-template/Dockerfile

    # GitHub repository for the template
    github:
      repo: bikram20/do-app-platform-ai-dev-workflow
      branch: main
      deploy_on_push: true

    # Service configuration
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-2gb  # 2GB RAM recommended for Rails

    # Ports
    http_port: 8080
    internal_ports:
      - 9090

    # Health check
    health_check:
      http_path: /dev_health
      port: 9090
      initial_delay_seconds: 60  # Rails takes longer to start
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 5

    # Build arguments - Enable Ruby and PostgreSQL
    build_args:
      - key: INSTALL_NODE
        value: "false"
      - key: INSTALL_PYTHON
        value: "false"
      - key: INSTALL_GOLANG
        value: "false"
      - key: INSTALL_RUST
        value: "false"
      - key: INSTALL_RUBY
        value: "true"  # Enable Ruby
      - key: RUBY_VERSIONS
        value: "3.4 3.3"
      - key: DEFAULT_RUBY
        value: "3.4"
      - key: INSTALL_POSTGRES
        value: "true"  # For production use
      - key: INSTALL_MONGODB
        value: "false"
      - key: INSTALL_MYSQL
        value: "false"

    # Environment variables
    envs:
      # === Your Rails Application Repository ===
      - key: GITHUB_REPO_URL
        value: "https://github.com/YOUR_USERNAME/rails-todo-app"
        scope: RUN_TIME

      # === GitHub Token (for private repos) ===
      - key: GITHUB_TOKEN
        value: ""
        scope: RUN_TIME
        type: SECRET

      # === Startup Command ===
      - key: DEV_START_COMMAND
        value: "bash dev_startup.sh"
        scope: RUN_TIME

      # === Workspace Configuration ===
      - key: WORKSPACE_PATH
        value: "/workspaces/app"
        scope: RUN_TIME

      # === Git Sync Configuration ===
      - key: GITHUB_SYNC_INTERVAL
        value: "30"
        scope: RUN_TIME

      - key: GITHUB_BRANCH
        value: "main"
        scope: RUN_TIME

      # === Rails Environment ===
      - key: RAILS_ENV
        value: "development"
        scope: RUN_TIME

      - key: RAILS_LOG_TO_STDOUT
        value: "true"
        scope: RUN_TIME

      # === Dev Health Server ===
      - key: ENABLE_DEV_HEALTH
        value: "true"
        scope: RUN_TIME

      - key: DEV_HEALTH_PORT
        value: "9090"
        scope: RUN_TIME

# Optional: Add PostgreSQL database for production
# databases:
#   - name: rails-db
#     engine: PG
#     production: false
#     version: "16"

# Note: In development, the app uses SQLite.
# To use PostgreSQL:
# 1. Uncomment the databases section above
# 2. Add DATABASE_URL to envs:
#    - key: DATABASE_URL
#      value: ${rails-db.DATABASE_URL}
#      scope: RUN_TIME
#      type: SECRET
# 3. Ensure config/database.yml production uses ENV["DATABASE_URL"]
