alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
ingress:
  rules:
  - component:
      name: blank-nodejs
    match:
      path:
        prefix: /
name: blank-nodejs-template
region: syd1
services:
- dockerfile_path: hot-reload-template/Dockerfile
  envs:
  - key: INSTALL_NODE
    scope: BUILD_TIME
    value: "true"
  - key: INSTALL_PYTHON
    scope: BUILD_TIME
    value: "false"
  - key: INSTALL_GOLANG
    scope: BUILD_TIME
    value: "false"
  - key: INSTALL_RUST
    scope: BUILD_TIME
    value: "false"
  - key: INSTALL_RUBY
    scope: BUILD_TIME
    value: "false"
  - key: INSTALL_POSTGRES
    scope: BUILD_TIME
    value: "false"
  - key: INSTALL_MONGODB
    scope: BUILD_TIME
    value: "false"
  - key: INSTALL_MYSQL
    scope: BUILD_TIME
    value: "false"
  - key: GITHUB_REPO_URL
    scope: RUN_TIME
    value: ${GITHUB_REPO_URL}
  - key: GITHUB_TOKEN
    scope: RUN_TIME
    type: SECRET
    value: ""
  - key: WORKSPACE_PATH
    scope: RUN_TIME
    value: /workspaces/app
  - key: GITHUB_SYNC_INTERVAL
    scope: RUN_TIME
    value: "30"
  - key: ENABLE_DEV_HEALTH
    scope: RUN_TIME
    value: "false"
  - key: DEV_START_COMMAND
    scope: RUN_TIME
    value: bash dev_startup.sh
  - key: GITHUB_REPO_FOLDER
    scope: RUN_TIME
    value: hot-reload-template/app-examples/blank-nodejs-template
  - key: GITHUB_BRANCH
    scope: RUN_TIME
    value: ${GITHUB_BRANCH}
  github:
    branch: main
    repo: ${GITHUB_REPO}
    deploy_on_push: false
  health_check:
    failure_threshold: 5
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    port: 8080
    success_threshold: 1
    timeout_seconds: 5
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: blank-nodejs
  source_dir: /
