#
# DigitalOcean App Platform Specification
# Simplified Development Environment with GitHub Sync
#
# This spec deploys a dev environment that automatically syncs a GitHub
# repository and runs your application for fast iteration cycles.
#

name: dev-environment
region: nyc

services:
  - name: dev-workspace
    # Use Dockerfile from repository
    dockerfile_path: hot-reload-template/Dockerfile

    # GitHub repository (this repository will be used for the dev environment itself)
    github:
      repo: bikram20/do-app-platform-ai-dev-workflow
      branch: main
      deploy_on_push: true

    # Service type - worker with HTTP health check
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb

    # Internal port for health check
    internal_ports:
    - 9090

    # HTTP port for your application traffic (health check uses dedicated port below)
    http_port: 8080

    # Health check configuration
    # Uses /dev_health endpoint which is always available (even without user app)
    health_check:
      http_path: /dev_health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 5
      port: 9090

    # Build arguments for runtime and database client installation
    # Enable only the runtimes you need for faster builds
    build_args:
      - key: INSTALL_NODE
        value: "true"  # Node.js/Next.js/Remix apps (optional - health server uses Go binary)
      - key: INSTALL_PYTHON
        value: "true"  # Python/FastAPI/Django apps
      - key: INSTALL_GOLANG
        value: "true"  # Go apps
      - key: INSTALL_RUST
        value: "false"  # Rust apps
      - key: INSTALL_RUBY
        value: "false"  # Ruby/Rails apps
      - key: RUBY_VERSIONS
        value: "3.4 3.3"
      - key: DEFAULT_RUBY
        value: "3.4"
      - key: INSTALL_POSTGRES
        value: "true"
      - key: INSTALL_MONGODB
        value: "false"
      - key: INSTALL_MYSQL
        value: "false"

    # Environment variables
    envs:
      # === GitHub Repository to Clone ===
      # Set this to the repository you want to work on
      - key: GITHUB_REPO_URL
        value: ""
        scope: RUN_TIME

      # === GitHub Authentication ===
      # Required for private repositories
      - key: GITHUB_TOKEN
        value: ""
        scope: RUN_TIME
        type: SECRET

      # === Workspace Configuration ===
      - key: WORKSPACE_PATH
        value: "/workspaces/app"
        scope: RUN_TIME

      - key: GITHUB_SYNC_INTERVAL
        value: "30"
        scope: RUN_TIME

      # === Dev Health Server ===
      # Built-in Go binary serving /dev_health on port 9090 for bootstrap health checks
      # Set to "false" when your app provides its own health endpoint
      - key: ENABLE_DEV_HEALTH
        value: "true"
        scope: RUN_TIME

      # === Application Startup ===
      # RECOMMENDED: Use a dev_startup.sh script to handle all corner cases.
      # Scripts can manage dependency installation, lock file conflicts, error recovery,
      # and hot reload properly. See hot-reload-template/examples/ for proven scripts.
      # 
      # Example: "bash dev_startup.sh"
      #
      # Simple commands (NOT RECOMMENDED - limited error handling):
      #   - "npm run dev -- --hostname 0.0.0.0 --port 8080"
      #   - "python app.py"
      #   - "go run main.go"
      #   - "uvicorn app:app --host 0.0.0.0 --port 8080"
      #   Note: Simple commands don't handle dependency installation, lock file conflicts,
      #   or automatic error recovery. Use scripts for production-ready setups.
      - key: DEV_START_COMMAND
        value: ""
        scope: RUN_TIME

      # === Monorepo Support ===
      # Specify subfolder within the repo to sync (for monorepos)
      - key: GITHUB_REPO_FOLDER
        value: ""
        scope: RUN_TIME

      # === Branch Selection ===
      # Specify which branch to sync (useful for feature/staging branches)
      - key: GITHUB_BRANCH
        value: ""
        scope: RUN_TIME

# Optional: Add alerts
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
